#!/bin/bash

set -e

# Parse image name for repo name
tagStart=$(expr index "$IMAGE_NAME" :)
repoName=${IMAGE_NAME:0:tagStart-1}
tag=${IMAGE_NAME:tagStart}
tagDot=$(expr index "$tag" .)
tagPart=${tag:0:tagDot-1}

# Tag and push image for each additional tag
for tag in {latest,$tagPart}; do
    docker tag $IMAGE_NAME ${repoName}:${tag}
    docker push ${repoName}:${tag}
done